### ISSUE TITLE
`question`: windows support

### ISSUE THREAD

**Issue by havenchyk** [mongodb-js/electron-installer-squirrel-windows#4]
Hi, does this package supports creation of msi/exe installer on the non-windows systems?

And what is the main difference between it and grunt-electron-installer?

**Comment by imlucas** [comment]
@havenchyk 

> Hi, does this package supports creation of msi/exe installer on the non-windows systems?

Not `.msi`.  [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) is what's really doing the heavy lifting here and it generates a self extracting `.exe`. If you're curious to see it in action, this is how we deliver MongoDB Compass on Windows: https://www.mongodb.com/download-center#compass

> And what is the main difference between it and grunt-electron-installer?

Same code and artifacts -grunt and -coffeescript.

**Comment by havenchyk** [comment]
@imlucas thanks, grunt and coffescript dependencies looks ugly :)

**Comment by stefanjudis** [comment]
Quick question. I'd prefer this module, because it doesn't have the grunt dep and is not coffee script.

But grunt-electron-installer support building for windows an mac currently ( using `mono` ). Are there plans to include this here?

**Comment by havenchyk** [comment]
@stefanjudis AFAIK, there are issues in the grunt-electron-installer with building for windows on non-windows OS.

**Comment by stefanjudis** [comment]
@havenchyk like what? Now that they switched to `mono` ( 6 days ago or something ) it looks promising. And I don't see open issues there?

**Comment by havenchyk** [comment]
@stefanjudis really? I missed it, probably this project is outdated in relation to grunt-electron-installer

**Comment by havenchyk** [comment]
@stefanjudis I don't see any recent commit. Is it in the any fork?

**Comment by stefanjudis** [comment]
https://github.com/atom/grunt-electron-installer/blob/master/index.coffee#L26-L31

https://github.com/atom/grunt-electron-installer/blob/master/index.coffee#L26-L31

https://github.com/atom/grunt-electron-installer/blob/master/index.coffee#L98-L100

**Comment by imlucas** [comment]
fwd'd to atom/grunt-electron-installer#91
